# Generated by Django 5.2.17 on 2026-08-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_saleshistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cleared', 'Cleared')], default='active', max_length=20),
        ),
    ]
