# Generated by Django 5.2.17 on 2026-09-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='last_expiry_notification_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
